In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1


## Introduction to Tensors

### Creating tensors

#### Scaler

In [3]:
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
scaler.item()

7

#### Vector

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

#### MATRIX

In [9]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX.shape

torch.Size([2, 2])

#### Tensor

In [13]:
TENSOR = torch.tensor([[[0, 1, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[0, 1, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0][1][1]

tensor(5)

### Random tensors

Why random tensors? Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Create a random tensor of size or shape of (3, 4)

In [17]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.7873, 0.7210, 0.3237, 0.0216],
         [0.2268, 0.1268, 0.4670, 0.4011],
         [0.3462, 0.0271, 0.4719, 0.6964]]])

Create an image with similar shape to an image, giving the tensor height, width, and colour channels (R, G, B).

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

create a tensor of all zeros

In [19]:
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Create tensor of all ones

In [20]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

do not use `torch.range` which is deprecated. Zeros like creates a tensor with the same shape as the input

In [22]:
one_to_ten = torch.arange(start=1, end=20, step=5)
one_to_ten

tensor([ 1,  6, 11, 16])

In [23]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0])

### Tensor datatypes and parameters

**Note:** Tensor datatypes is of the 3 mostlikkly errors you will in counter with PyTorch & Deep learning. Below a list of the most common errors:
1. Tensors not of the right datatype
2. Tensors not of the right shape
3. Tensors not on the right device

Attributes of a tensor:
* **dtype**: defines what datatype the tensor is (eg. float32 or float16)
* **device**: by default cpu, can be changed to cuda
* **grad**: Whether to track gradients when working with this tensor.

In [24]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Getting enformation

1. Tensors not of the right datatype - to get the datatype from the tensor you can use `tensor.dtype`
2. Tensors not of the right shape - to get the shaper from a tensor, you can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor you can use `tensor.device`

Lets create a tensor and try these 3 out.

! shape & size() do the same thing, but shape is an attribute, size is a function.

In [27]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5261, 0.0704, 0.4760, 0.9958],
        [0.2905, 0.8430, 0.2461, 0.0351],
        [0.2785, 0.7027, 0.8518, 0.8689]])

In [28]:
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Tensor is located on the: {some_tensor.device}')

tensor([[0.5261, 0.0704, 0.4760, 0.9958],
        [0.2905, 0.8430, 0.2461, 0.0351],
        [0.2785, 0.7027, 0.8518, 0.8689]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Tensor is located on the: cpu


### Manipulationg Tensors

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Decision
* Matrix multiplication

#### Element-wise operations

Below we create a tensor, and go down the list and add an example for each element wise operation.

In [29]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [30]:
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor - 10

tensor([-9, -8, -7])

In [32]:
tensor * 10

tensor([10, 20, 30])

In [33]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [34]:
tensor_2 = torch.tensor([8, 7, 9])
print(tensor, ' * ', tensor_2, ' = ', tensor * tensor_2)

tensor([1, 2, 3])  *  tensor([8, 7, 9])  =  tensor([ 8, 14, 27])


This can also be done using the build in funcunions in torch

In [35]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [36]:
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

In [37]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.divide(tensor, 10)

tensor([0.1000, 0.2000, 0.3000])

#### Matrix operations

Matrix multiplication or the dot product, is the act of multiplying two matrix's.

!how do i fucking show matrix multiplications in mark down?

[1 2 3]   [ 7  8 ]   [  58  64 ]
[4 5 6] * [ 9 10 ] = [ 139 154 ]
          [11 12 ]

* (1, 2, 3) • (7, 9, 11) = 1×7 + 2×9 + 3×11 = 58
* (1, 2, 3) • (8, 10, 12) = 1×8 + 2×10 + 3×12 = 64
* (4, 5, 6) • (7, 9, 11) = 4×7 + 5×9 + 6×11 = 139
* (4, 5, 6) • (8, 10, 12) = 4×8 + 5×10 + 6×12 = 154

example from above found here (https://www.mathsisfun.com/algebra/matrix-multiplying.html)

#### Rules
There are two main rules that performing matrix multiplications needs to satisfy:
1. The **inner dimensions** must match:
    * (3, 2) @ (3, 2) won't work
    * (2, 3) @ (3, 2) will work
    * (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the **outer dimensions**
    * (2, 3) @ (3, 2) -> (2, 2)
    * (3, 2) @ (2, 3) will work

In [39]:
%%time

torch.matmul(tensor, tensor_2)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(49)

In [40]:
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
tensor_2 = torch.tensor([[ 7,  8],
                         [ 9, 10],
                         [11, 12]])

print(tensor, '\n', 'X \n' , tensor_2 , '\n = \n' , torch.matmul(tensor, tensor_2))

tensor([[1, 2, 3],
        [4, 5, 6]]) 
 X 
 tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]]) 
 = 
 tensor([[ 58,  64],
        [139, 154]])


In [41]:
%%time
# Matrix multiplication by hand

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor([17, 29, 45])
CPU times: total: 31.2 ms
Wall time: 997 µs


In [42]:
%%time

torch.matmul(tensor, tensor_2)

CPU times: total: 0 ns
Wall time: 0 ns


tensor([[ 58,  64],
        [139, 154]])

In [43]:
# Operator for matrix multiplecations

tensor @ tensor_2

tensor([[ 58,  64],
        [139, 154]])

#### How to handle shape errors for matrix multiplications


In [44]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B)

In [45]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a transpose. A transpose switches the axes or dimensions of a given tensor.

In [46]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [47]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [48]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean,sum, etc (tensor aggregation)

In [49]:
tensor = torch.arange(1, 100, 10)

In [50]:
# Finding the min
torch.min(tensor), tensor.min()

(tensor(1), tensor(1))

In [51]:
# Finding the max
torch.max(tensor), tensor.max()

(tensor(91), tensor(91))

In [52]:
# Find the mean - note torch.mean() requires a tensor of float data type
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [53]:
# Find the sum
torch.sum(tensor), tensor.sum()

(tensor(460), tensor(460))

###  Finding the positional min and max

Find the position in tensor that has the minimum value with argmin() -> returns index position of targer tensor where the minimum value occurs

In [54]:
tensor.argmin()

tensor(0)

In [55]:
tensor[0]

tensor(1)

In [56]:
tensor[tensor.argmax()]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - Reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - Combine multiple tensors verticaly or horizontaly
* Squeeze - Remove all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tesnor
* Permute - Return a view of the input with the dimensions swapped in a certain way

let's create a tensor

In [57]:
import torch
tensor = torch.arange(1., 13.)
tensor, tensor.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

To this tensor we can add an other dimension

In [58]:
reshaped_tensor = tensor.reshape(3, 4)
reshaped_tensor, reshaped_tensor.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

Now lets change the view

In [59]:
change_view_tensor = tensor.view(1, 12)
change_view_tensor, change_view_tensor.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

changing change_view_tensor changes tensor (because a view of a tensor shares the same memory as the original)

In [60]:
change_view_tensor[:, 0] = 5
change_view_tensor, tensor

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

Stack tensors on top of each other

In [61]:
stacked_tensor = torch.stack([tensor, tensor, tensor], dim=1)
stacked_tensor, stacked_tensor.shape

(tensor([[ 5.,  5.,  5.],
         [ 2.,  2.,  2.],
         [ 3.,  3.,  3.],
         [ 4.,  4.,  4.],
         [ 5.,  5.,  5.],
         [ 6.,  6.,  6.],
         [ 7.,  7.,  7.],
         [ 8.,  8.,  8.],
         [ 9.,  9.,  9.],
         [10., 10., 10.],
         [11., 11., 11.],
         [12., 12., 12.]]),
 torch.Size([12, 3]))

torch.squeeze() removes all single dimensions from a target tensor. Unsqueeze adds the dimension

In [62]:
change_view_tensor, change_view_tensor.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [63]:
change_view_tensor = change_view_tensor.squeeze()
change_view_tensor, change_view_tensor.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [64]:
dimensions = 0
change_view_tensor.unsqueeze(dimensions), change_view_tensor.unsqueeze(dimensions).shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [65]:
image_tensor = torch.rand(size=(224, 224, 3))
permuted_image_tensor = image_tensor.permute(2, 0, 1)
permuted_image_tensor.shape

torch.Size([3, 224, 224])

## Indexing in tensors

In [66]:
import torch
tensor = torch.arange(1, 10).reshape(1, 3, 3)
tensor, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [67]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
tensor[0, 2]

tensor([7, 8, 9])

In [69]:
tensor[0, 2, 2]

tensor(9)

In [70]:
tensor[:, 2, 2]

tensor([9])

In [71]:
tensor[0, 0, :]

tensor([1, 2, 3])

In [73]:
tensor[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python computing library, and because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor - > NumPy -> `torch.Tensor.numpy()`

The NumPy default data type is float64, if converted to tensor, it will take this default vallue unless specified.

In the following exemple we turn a NumPy array into a tensor:

In [76]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [77]:
array.dtype

dtype('float64')

In [78]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take the random out of random)

To reduce the randomness in neural networks and PyTorch comes the concept of a * random seed *. Essentially the seed is a way to "flavour" the randomness.


In [81]:
import torch

RANDOM_SEED = 115

torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1996, 0.6411, 0.9102, 0.0929],
        [0.9051, 0.9735, 0.6610, 0.6851],
        [0.3352, 0.6306, 0.7783, 0.1538]])
tensor([[0.1996, 0.6411, 0.9102, 0.0929],
        [0.9051, 0.9735, 0.6610, 0.6851],
        [0.3352, 0.6306, 0.7783, 0.1538]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch object on GPU

GPU = faster computation on numbers, tanks to nvidiea

### 1. Getting a GPU

1. Easiest - use Google Colab for free GPU
2. Get your own (Need set up)
3. Use cloud cloud computing - GCP, AWS, Azure

For 2, 3 PyTorch + GPU drivers taks a little set up. Follow this [link](https://pytorch.org/get-started/locally/)

### 2. Check for GPU Acces with PyTjorch

In [1]:
import torch
torch.cuda.is_available()

False

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [5]:
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU

When you create a tensor by default it is created on CPU

In [2]:
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

### 4. Moving tensors to cpu

If a tensor is on gpu it cant be converted to numpy. To migrate it back we can use the following commands.

In [7]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3], dtype=int64)

## Exercise

on the [course site](https://www.learnpytorch.io/) there are possible exercises